production:
  application: "test-loadbalancer"
  repo_url: "git@github.com:ShadowNox96/test-loadbalancer.git"
  deploy_to: "/home/ubuntu/apps/test-loadbalancer"
  ssh_port: 22
  server: "35.88.135.43"
  server_name: "emanueldev.space"
  db_server: "localhost"
  user: "ubuntu"
  db_user: "dbuser"
  db_password: "dbpassword"
  rvm_ruby_version: "3.0.0"
  stage: "production"
  branch: "main"
  rails_env: "production"
  enable_ssl: false

  
