production:
  application: "test-loadbalancer"
  repo_url: "git@github.com:ShadowNox96/test-loadbalancer.git"
  deploy_to: "/home/ubuntu/apps/test-loadbalancer"
  ssh_port: 22
  server: "34.216.108.123"
  server_name: "emanueldev.space"
  db_server: "localhost"
  user: "ubuntu"
  db_user: "test"
  db_password: ""
  rvm_ruby_version: "3.0.0"
  stage: "production"
  branch: "main"
  rails_env: "production"
  enable_ssl: false

  
